# Generated by Django 3.2.4 on 2021-12-13 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_auto_20211212_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instructions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.CharField(max_length=2000000)),
                ('course', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.course')),
            ],
        ),
    ]
