# Generated by Django 3.2.4 on 2022-08-03 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0028_listening'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='mp3file',
        ),
    ]
