# Generated by Django 3.2.4 on 2022-08-03 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0029_remove_question_mp3file'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='mp3file',
            field=models.FileField(default=True, upload_to=''),
        ),
    ]
