# Generated by Django 3.2.4 on 2022-08-03 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0032_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='exanmname',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.exam'),
        ),
    ]
